[package]
name = "uniffi-example-geometry"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "uniffi_geometry"

[dependencies]
uniffi = "0.23.0"

[build-dependencies]
uniffi = {version = "0.23.0", features = ["build"] }
